name: Build chiaki-ng Appimage x86_64

on:
  workflow_dispatch:

jobs:
  build-appimage_x64:
    name: Build chiaki-ng appimage_x64
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: 'chiaki-ng'

      - name: Add QmlWebEngine Import
        working-directory: chiaki-ng
        run: |
          cp scripts/qtwebengine_import.qml gui/src/qml/
  
      - name: Run build script
        working-directory: chiaki-ng
        run: |
          set -xe
          podman run --rm \
            -v "`pwd`:/build/chiaki" \
            -w "/build/chiaki" \
            --device /dev/fuse \
            --cap-add SYS_ADMIN \
            -t docker.io/streetpea/chiaki-ng-builder:qt6.7 \
            /bin/bash -c "sudo -E scripts/build-appimage.sh /build/appdir"
          

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-ng.AppImage_x86_64
          path: chiaki-ng/appimage/chiaki-ng.AppImage
          if-no-files-found: error
          retention-days: 7
